class HashMap:
    def __init__(self, cap=4):
        self.cap = cap
        self.size = 0
        self.backits = [[] for _ in range(cap)]

    def put(self, key, value): ...

    def get(self, key): ...

    def remove(self, key): ...

    def contains_key(self, key): ...

    def contains_value(self, value): ...

    def size(self):
        return self.size

    def is_empty(self):
        return self.size == 0

    def clear(self): ...

    def resize(self, new_capacity): ...

    def load_factor(self): ...

    def keys(self): ...

    def values(self): ...

    def items(self): ...

    def _hash(self, key):
        return hash(key) % self.cap

    def _find_slot(self, key): ...

    def _rehash(self): ...
